"""Save stats to database

Revision ID: 51b020239fe4
Revises: ad56d28c7bc7
Create Date: 2017-03-13 19:51:33.110274

"""

# revision identifiers, used by Alembic.
revision = '51b020239fe4'
down_revision = 'ad56d28c7bc7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_simulations', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_simulations', 'stats')
    # ### end Alembic commands ###
