"""Create initial tables

Revision ID: 6f32bf03c712
Revises: 
Create Date: 2016-02-09 22:45:56.451694

"""

# revision identifiers, used by Alembic.
revision = '6f32bf03c712'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('pdc_ranking', sa.Integer(), nullable=True),
    sa.Column('red_dragon_ranking', sa.Integer(), nullable=True),
    sa.Column('ddb_ranking', sa.Integer(), nullable=True),
    sa.Column('ddb_popularity', sa.Integer(), nullable=True),
    sa.Column('career_earnings', sa.Float(), nullable=True),
    sa.Column('career_9_darters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.Integer(), nullable=True),
    sa.Column('tv_coverage', sa.String(), nullable=True),
    sa.Column('sponsor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_players',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_players')
    op.drop_table('matches')
    op.drop_table('events')
    op.drop_table('tournaments')
    op.drop_table('players')
    ### end Alembic commands ###
