"""Add last_updated column for all tables

Revision ID: 9d182648f0e9
Revises: 405e990152ba
Create Date: 2016-02-10 10:18:49.799648

"""

# revision identifiers, used by Alembic.
revision = '9d182648f0e9'
down_revision = '405e990152ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('match_results', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('matches', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'last_updated')
    op.drop_column('players', 'last_updated')
    op.drop_column('matches', 'last_updated')
    op.drop_column('match_results', 'last_updated')
    op.drop_column('events', 'last_updated')
    ### end Alembic commands ###
