"""Add always_check column to events

Revision ID: cacc6a13f2d7
Revises: 515c77951c92
Create Date: 2016-02-21 18:27:15.736347

"""

# revision identifiers, used by Alembic.
revision = 'cacc6a13f2d7'
down_revision = '515c77951c92'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('always_check', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'always_check')
    ### end Alembic commands ###
