"""Add cols to events

Revision ID: d4b287aba120
Revises: 9d182648f0e9
Create Date: 2016-02-13 21:44:13.369802

"""

# revision identifiers, used by Alembic.
revision = 'd4b287aba120'
down_revision = '9d182648f0e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(), nullable=True))
    op.add_column('events', sa.Column('prize_fund', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('winner_player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'players', ['winner_player_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'winner_player_id')
    op.drop_column('events', 'prize_fund')
    op.drop_column('events', 'category')
    ### end Alembic commands ###
