"""Add match simulations

Revision ID: e72943a6f370
Revises: 51b020239fe4
Create Date: 2017-03-26 16:27:42.555640

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e72943a6f370'
down_revision = '51b020239fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'match_simulations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match_type', sa.Enum('match_play', 'set_play', 'premier_league', name='match_types'), nullable=False),
        sa.Column('profile_a_id', sa.Integer(), nullable=True),
        sa.Column('profile_b_id', sa.Integer(), nullable=True),
        sa.Column('a_first', sa.Boolean(), nullable=False),
        sa.Column('iterations', sa.Integer(), nullable=False),
        sa.Column('a_handicap', sa.Integer(), nullable=False),
        sa.Column('b_handicap', sa.Integer(), nullable=False),
        sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('run_time', sa.DateTime(), nullable=True),
        sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['profile_a_id'], ['profiles.id'], ),
        sa.ForeignKeyConstraint(['profile_b_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('table_updates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_simulations')
    # ### end Alembic commands ###
